version: 0.2

phases:
  pre_build:
    commands:
      - echo Downloading GAMESS source tarball from S3...
      - aws s3 cp s3://gamess-source/gamess-2024.2.1.tar.gz .
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t gamess .
  post_build:
    commands:
      - echo Tagging Docker image...
      - docker tag gamess:latest $ECR_REPO_URI:latest
      - echo Pushing Docker image to ECR...
      - docker push $ECR_REPO_URI:latest
      - echo Extracting install.info from container...
      - container_id=$(docker create gamess)
      - docker cp $container_id:/opt/gamess/install.info .
      - docker rm $container_id

artifacts:
  files:
    - install.info
